### ISSUE TITLE
Service API

### ISSUE THREAD

**Issue by egin10** [nadirbasalamah/klinikapps#1]
apakah kedepannya akan dibuat sebuah service API untuk konsumsi mobile apps?

**Comment by nadirbasalamah** [comment]
Iya, nanti akan dibuat namun kemungkinan waktu pengerjaan akan cukup lama dikarenakan saya masih banyak tugas proyek akhir.

**Comment by egin10** [comment]
baik, terimakasih informasinya.

apakah pengguna lain bisa berkontribusi di repo ini ?

**Comment by nadirbasalamah** [comment]
Sama-sama. Pengguna lain dapat berkontribusi di repo ini.

**Comment by egin10** [comment]
baik, terimakasih informasinya
